source "http://rubygems.org"

gem "rails", "3.0.7"
gem 'mysql'
gem 'rake', '~> 0.8.7'

# gem 'authlogic'
# TODO this is temporary until the official authlogic gem is updated for rails 3
gem 'authlogic', :git => 'git://github.com/binarylogic/authlogic.git'
gem "bcrypt-ruby", :require => "bcrypt"
gem "jammit"

# TODO this is temporary until a new version of loofah is released. loofah is required by feedzirra. This forces the version that works with rails3
gem 'loofah'

gem 'muck-engine', :path => "~/projects/muck-engine"
gem 'muck-users', :path => "~/projects/muck-users"
gem 'muck-profiles', :path => "~/projects/muck-profiles"
gem 'muck-activities', :path => "~/projects/muck-activities"
gem "muck-contents", :path => "~/projects/muck-contents"
gem "muck-comments", :path => "~/projects/muck-comments"
gem "muck-shares", :path => "~/projects/muck-shares"
gem 'muck-services', :path => '../'  
  
if RUBY_VERSION < '1.9'
  gem "ruby-debug"
end

group :test, :development do
  gem "rspec-rails", ">=2.4.0"
  gem "cucumber-rails"
end

group :test do
  gem "capybara", ">= 0.3.9"
  gem "shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec", ">=2.4.0"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end